AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket containing content for ElasticBeanstalk
Parameters:
  BucketName:
    Description: S3 bucket name
    Type: String
Resources:
  ContentBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
